### ISSUE TITLE
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-yaml#184] opened 2022-05-02 01:06 UTC
I tried to deploy this program using YAML and AWSX - and hit the error below.  I've not seen this before.  It seems to be entirely within the Go SDK - but I'm assuming it's something related to how we are registering resources with YAML?

```yaml
name: awsx
runtime: yaml
resources:
  cluster:
    type: aws:ecs:Cluster
  lb:
    type: awsx:lb:ApplicationLoadBalancer
  nginx:
    type: awsx:ecs:FargateService
    properties:
      cluster: ${cluster.arn}
      taskDefinitionArgs:
        container:
          image: nginx:latest
          cpu: 512
          memory: 128
          portMappings:
            - containerPort: 80
              targetGroup: ${lb.defaultTargetGroup}
outputs:
  url: ${lb.loadBalancer.dnsName}
```

```
  pulumi:pulumi:Stack (awsx-dev):
    panic: reflect.Value.Interface: cannot return value obtained from unexported field or method
    goroutine 131 [running]:
    reflect.valueInterface({0x1b8b720, 0xc00e984ef8, 0x1bbc0cf}, 0x6)
        /usr/local/Cellar/go/1.17.2/libexec/src/reflect/value.go:1362 +0xd9
    reflect.Value.Interface(...)
        /usr/local/Cellar/go/1.17.2/libexec/src/reflect/value.go:1351
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x1ac9760, 0xc00e984e40}, {0x1d840d0, 0x1a4efa0}, 0x1, 0x0)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:468 +0x1ff5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x1b684a0, 0xc00c936380}, {0x1d840d0, 0x1a4efa0}, 0x1, 0xe8)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:273 +0xc5d
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:217
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x1a6d720, 0xc00c92e990}, {0x1d840d0, 0x1a4efa0}, 0x1, 0x91)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:447 +0x22c7
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:217
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x1a06820, 0xc006b0a930}, {0x1d840d0, 0x1a4efa0}, 0x1, 0xe8)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:421 +0x1b66
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:217
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x1a6d720, 0xc00c92e960}, {0x1d840d0, 0x1a4efa0}, 0x1, 0xe7)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:447 +0x22c7
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:217
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x1a6d720, 0xc00c92e930}, {0x1d840d0, 0x1a4efa0}, 0x1, 0xe6)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:447 +0x22c7
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:217
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs.func1({0xc000812288, 0x12}, {0x1a6d720, 0xc00c92e930}, {0x1d840d0, 0x1a4efa0})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:134 +0x8b
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs({0x1d47d20, 0xc00c92e6f0})
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/rpc.go:197 +0x643
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).prepareResourceInputs(0xc00014cb40, {0x1d7b780, 0xc0065fa2a0}, {0x1d47d20, 0xc00c92e6f0}, {0xc0043c1f68, 0x17}, 0xc004fd6360, 0xc00c934090, 0x1)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/context.go:1248 +0x1a5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource.func1()
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/context.go:809 +0x27f
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.30.1-0.20220425210338-85c9458052e7/go/pulumi/context.go:796 +0x7c8
```

**Comment by iwahbe** [comment] 2022-05-05 16:58
@lukehoban What versions (pulumi,yaml,awsx) are you using?

**Comment by AaronFriel** [comment] 2022-05-05 18:54
Closing this as cannot reproduce, re-opening a different issue with the same program in #193.

**Closed** 2022-05-05 18:54 UTC
Labels: kind/bug, resolution/no-repro
